# Generated by Django 3.0.7 on 2020-06-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(height_field='height', upload_to='uploads/%Y/%m/%d/', width_field='width'),
        ),
    ]
