# Generated by Django 3.0.7 on 2020-06-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200622_1835"),
    ]

    operations = [
        migrations.AlterField(model_name="dog", name="image", field=models.ImageField(upload_to="uploads/"),),
        migrations.AlterField(model_name="dog", name="rating", field=models.IntegerField(default=1000),),
    ]
